#!/bin/bash

ORIG_FILE=$HOME/Dropbox/youtube/ERRORS
FILE=$HOME/Dropbox/youtube/ERRORS_BACKUP
mv $ORIG_FILE $FILE
NUM_VIDS=$(wc -l "$FILE" | cut -f 1 -d " ")
notify-send "redownloading $NUM_VIDS video/s"
while read line; do
	my_youtube_dl.sh "$line"
done < $FILE
rm $FILE
