#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

cd $HOME/Videos

CATEGORIES=$(fd --strip-cwd-prefix -t d --max-depth 1)
CATEGORY=$(echo "$CATEGORIES"\
	| sort -r | rofi -dmenu -p "$1" -i -l 10)

if [ -d "$CATEGORY" ]; then
	echo $CATEGORY
	cd "$CATEGORY"
	SELECTED=$(fd --strip-cwd-prefix -t f \
	-e 'mkv' \
	-e 'mp4' \
	-e 'wmv' \
	-e 'flv' \
	-e '.webm' \
	-e 'mov' \
	-e '.avi' \
	 | sort | rofi -dmenu -p "$1" -i -l 30 -theme-str 'window {width:70%;}')
	 # | sort | dmenu $DMENU_STYLE -p "$1" -i -l 30)

	if [ -f "$SELECTED" ]; then
		echo $SELECTED
		echo $1
		if [ ! $1 ] || [ $1 != "nohistory" ]; then
			echo "History mode"
			echo $HOME/Videos/"$CATEGORY"/"$SELECTED" >> $HOME/Videos/WATCHED
			echo $HOME/Videos/"$CATEGORY"/"$SELECTED" >> $HOME/Videos/HISTORY
		fi
		mpv "$SELECTED"
	fi
fi


