#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

SELECTED=$(ls $HOME/scripts/small_scripts | rofi -dmenu -l 10 -i -p "Run:")
# SELECTED=$(ls $HOME/scripts/small_scripts | dmenu $DMENU_STYLE -i -l 30 -p "Run:")

exec "$SELECTED"
