#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

DIR="/home/eyal/Dropbox/uni/research/PhD/thoughts"
VIM_CMD="nvim --listen /tmp/tex"

cd "$DIR"
SELECTED=$(fd --strip-cwd-prefix -e tex | sort --reverse | \
dmenu $DMENU_STYLE -i -l 30)
FILE="$DIR"/"$SELECTED"
if [ -f $FILE ]; then
	exec xfce4-terminal -e "$VIM_CMD $FILE"
else
	exec /home/eyal/scripts/dmenu_thoughts_create
fi
