#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

VID=$(xclip -out)
VID=$(echo "$VID" | sed 's/&.*//')
CMD=$(echo -e 'Download\nWatch' | dmenu -i -l 10 -p $VID)
if [ "$CMD" == "Watch" ] 
then 
	notify-send "starting $VID..."
	mpv "$VID"
elif [ "$CMD" == "Download" ] 
then
	notify-send "downloading $VID..."
	OUTDIR="$HOME"/Videos/youtube/
	OUTFORMAT="%(uploader)s - %(title)s.%(ext)s"
	if youtube-dl -o "$OUTDIR""$OUTFORMAT" "$VID"
	then
		notify-send "finished downloading $VID!"
	else
		notify-send -u critical "ERROR downloading $VID!"
		echo "$VID" >> "$OUTDIR"ERRORS
	fi
fi

