#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

DIR="/home/eyal/Dropbox/uni/research/PhD/thoughts"

SELECTED=$(ls -r "$DIR" | grep ^[0-9] | grep -v ~$ | cut -d "." -f 1 | uniq | \
dmenu $DMENU_STYLE -i -l 30)

if [ -n "$SELECTED" ]; then
	FILE=$(ls "$DIR" | grep "$SELECTED" | grep -v ~$ | \
	dmenu $DMENU_STYLE -i -l 30)

	exec xdg-open "$DIR"/"$FILE"
fi
