#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

SELECTED=$(find $HOME/Videos/youtube -type f \
-name '*.mkv' \
-o -name '*.mp4' \
-o -name '*.wmv' \
-o -name '*.flv' \
-o -name '*.webm' \
-o -name '*.mov' \
-o -name '*.avi' \
 | sort | dmenu $DMENU_STYLE -i -l 30)

if [ "$SELECTED" ]; then
	echo "$SELECTED" >> $HOME/Videos/WATCHED
	echo "$SELECTED" >> $HOME/Videos/HISTORY
	mpv "$SELECTED"
fi
