#!/bin/bash

unset LANG
source /etc/profile.d/locale.sh

DIR="/home/eyal/Dropbox/uni/research/PhD/thoughts"

cd "$DIR"
SELECTED=$(fd --strip-cwd-prefix -e tex | \
dmenu $DMENU_STYLE -i -l 30)
exec xfce4-terminal -e "vim --servername vimd $DIR/$SELECTED"
