#!/bin/bash

~/Dropbox/dev/rofi-keepassxc/rofi-keepassxc ~
unset LANG
source /etc/profile.d/locale.sh

cd $HOME/Videos

CATEGORY=$(fd --strip-cwd-prefix -t d \
	| rofi -dmenu -p "$1" -i -l 10)
	# | dmenu $DMENU_STYLE -p "$1" -i -l 30)

if [ -d "$CATEGORY" ]; then
	echo $CATEGORY
	cd "$CATEGORY"
	SELECTED=$(fd --strip-cwd-prefix -t f \
	-e 'mkv' \
	-e 'mp4' \
	-e 'wmv' \
	-e 'flv' \
	-e '.webm' \
	-e 'mov' \
	-e '.avi' \
	 | sort | rofi -dmenu -p "$1" -i -l 30)
	 # | sort | dmenu $DMENU_STYLE -p "$1" -i -l 30)

	if [ -f "$SELECTED" ]; then
		echo $SELECTED
		echo $1
		if [ ! $1 ] || [ $1 != "nohistory" ]; then
			echo "History mode"
			echo $HOME/Videos/"$CATEGORY"/"$SELECTED" >> $HOME/Videos/WATCHED
			echo $HOME/Videos/"$CATEGORY"/"$SELECTED" >> $HOME/Videos/HISTORY
		fi
		mpv "$SELECTED"
	fi
fi


