#!/bin/bash
rsync -uvrP --delete-after /home/eyal/Dropbox/dev/website/ root@ysfm.co.il:/var/www/homepage/
rsync -uvrP --delete-after /home/eyal/Dropbox/uni/website/ seelig@math.huji.ac.il:/home/staff/seelig/public_html/
